/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cvrptwpd_CONSTANTS_H
#define cvrptwpd_CONSTANTS_H

#include "cvrptwpd_types.h"



class cvrptwpdConstants {
 public:
  cvrptwpdConstants();

};

extern const cvrptwpdConstants g_cvrptwpd_constants;



#endif
